### ISSUE TITLE
Support for `includes-script` in custom places

### ISSUE THREAD

**Issue by drdanz** [mithro/actions-includes#14]
It would be nice to be able to include scripts in custom places with custom tags. 

For example, it would be nice if a script could be inserted using the `command` tag in when using the [nick-invision/retry](https://github.com/nick-invision/retry) action

**Comment by mithro** [comment]
Any idea on what could be a workable syntax?

**Comment by drdanz** [comment]
Perhaps something like this?

```yml
uses: nick-invision/retry@v2
with:
  timeout_minutes: 10
  max_attempts: 3
  includes-script: [ "command", script.py ]
```

This should expand to

```yml
uses: nick-invision/retry@v2
with:
  timeout_minutes: 10
  max_attempts: 3
  shell: python
  command: |
    <script.py content>
```

**Comment by mithro** [comment]
## Option 1

```yml
uses: nick-invision/retry@v2
with:
  timeout_minutes: 10
  max_attempts: 3
  includes-script:
    command: script.py
```
should expand to
```yml
uses: nick-invision/retry@v2
with:
  timeout_minutes: 10
  max_attempts: 3
  shell: python
  command: |
    <script.py content>
```

-----

Then also;

```yml
uses: nick-invision/retry@v2
with:
  timeout_minutes: 10
  max_attempts: 3
  includes-script: script.py
```
is equivalent to
```yml
uses: nick-invision/retry@v2
with:
  timeout_minutes: 10
  max_attempts: 3
  includes-script:
    runs: script.py
```

## Option 2 -- `outputs` dictionary

```yml
uses: nick-invision/retry@v2
with:
  timeout_minutes: 10
  max_attempts: 3
  includes-script:
    uses: script.py
    outputs:
      script: command
      shell: shell-type
```
should expand to
```yml
uses: nick-invision/retry@v2
with:
  timeout_minutes: 10
  max_attempts: 3
  shell-type: python
  command: |
    <script.py content>
```

-----

Then also;

```yml
uses: nick-invision/retry@v2
with:
  timeout_minutes: 10
  max_attempts: 3
  includes-script: script.py
```
is equivalent to
```yml
uses: nick-invision/retry@v2
with:
  timeout_minutes: 10
  max_attempts: 3
  includes-script:
    uses: script.py
    outputs:
      script: runs
      shell: shell
```

## Option 3 -- `includes-script` under key

```yml
uses: nick-invision/retry@v2
with:
  timeout_minutes: 10
  max_attempts: 3
  command:
    includes-script: script.py
```
should expand to
```yml
uses: nick-invision/retry@v2
with:
  timeout_minutes: 10
  max_attempts: 3
  shell-type: python
  command: |
    <script.py content>
```

-----

Then also;

```yml
uses: nick-invision/retry@v2
with:
  timeout_minutes: 10
  max_attempts: 3
  runs:
    includes-script: script.py
```
is equivalent to
```yml
uses: nick-invision/retry@v2
with:
  timeout_minutes: 10
  max_attempts: 3
  runs: |
    <script>
```

## Option 4 - `!include`

Use same syntax as https://github.com/codeindulgence/yaml-includes and https://www.home-assistant.io/docs/configuration/splitting_configuration/ and https://pypi.org/project/pyyaml-include/

```yml
uses: nick-invision/retry@v2
with:
  timeout_minutes: 10
  max_attempts: 3
  command: !include: script.py
```
should expand to
```yml
uses: nick-invision/retry@v2
with:
  timeout_minutes: 10
  max_attempts: 3
  shell-type: python
  command: |
    <script.py content>
```

-----

Then also;

```yml
uses: nick-invision/retry@v2
with:
  timeout_minutes: 10
  max_attempts: 3
  runs: !include: script.py
```
is equivalent to
```yml
uses: nick-invision/retry@v2
with:
  timeout_minutes: 10
  max_attempts: 3
  runs: |
    <script>
```
