### ISSUE TITLE
Fix comments lining up from included actions

### ISSUE THREAD

**Issue by mithro** [mithro/actions-includes#21]
They need to be indented more.

**Comment by mike-potter** [comment]
Also, some comments get stripped from the main action file.

Example src file:
```
jobs:
  my-job:
    name: My Job
    runs-on: self-hosted
    container:
      # Private Repos: https://github.blog/changelog/2020-09-24-github-actions-private-registry-support-for-job-and-service-containers/
      image: myimage
      # Default actions run as user 1000 (ubuntu)
      # https://stackoverflow.com/questions/58955666/how-to-set-the-docker-user-in-github-actions
      options: --user 1000
    steps:
      - includes: ./.github/includes/my-include
```
results in the compiled action file:
```
jobs:
  my-job:
    name: My Job
    runs-on: self-hosted
    container:
      # Private Repos: https://github.blog/changelog/2020-09-24-github-actions-private-registry-support-for-job-and-service-containers/
      image: myimage
      options: --user 1000
    steps:
    - name: ⏰ 🛂 📕 - Checking workflow expansion is up to date
   ...
```
Notice the comment about "Default actions run as..." between the "image:" and "options:" keys is removed.
